"""Demo data, and making sure it can never be mistaken for real revenue.

`app.cli.seed_demo` writes rows so the dashboard has something to render before
a single agent has ever paid. That is useful and it is also the most dangerous
thing in the repository: a screenshot of fabricated USDC revenue, presented as a
payment gateway's ledger, is a lie whether or not anyone meant it.

So the guarantee is structural, at four levels, and every level is checkable:

1. **Schema.** Every table has `is_demo` (migration 0002). There is no "demo
   session id prefix" convention to forget.
2. **Writer.** `seed_demo` goes through `mark_demo()` and nothing else; a test
   asserts the seeder cannot produce a row with `is_demo=False`.
3. **Receipt body.** A demo receipt's canonical JSON carries `"isDemo": true`
   *inside* the hashed body, so a receipt copied out of the database into a
   slide still says what it is, and the flag cannot be edited off without
   breaking `body_hash`.
4. **Read.** `summary()` here is the one call the dashboard and the admin make
   to decide whether to show the banner. `BANNER` is the wording.

`real_only(Model)` / `demo_only(Model)` build the filter clause -- use them
rather than writing `Model.is_demo == False` by hand, so "which reads exclude
demo data" is one grep, not six.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, TypeVar

from sqlalchemy import func
from sqlmodel import select  # sqlmodel's select, so Session.exec() types line up

from app.models import Author, Batch, Call, PaySession, Receipt, Tool

if TYPE_CHECKING:  # pragma: no cover - typing only
    from sqlmodel import Session as DBSession

__all__ = [
    "BANNER",
    "BANNER_SHORT",
    "DEMO_TAG",
    "LEDGER_MODELS",
    "DemoSummary",
    "mark_demo",
    "summary",
    "demo_only",
    "real_only",
    "purge",
]

#: Shown by the dashboard whenever `summary().present` is true. Deliberately
#: unambiguous: it names the command that produced the rows so a reader can
#: check, and it says the tx hashes are not real, because that is the specific
#: thing a viewer would otherwise assume.
BANNER = (
    "DEMO DATA - these sessions, calls, batches and receipts were generated by "
    "`python -m app.cli seed_demo`. No payment was authorized, no USDC moved, "
    "and the transaction hashes below are synthetic. Run "
    "`python -m app.cli seed_demo --reset-only` to remove every row of it."
)

#: For a chip/badge next to a number, where BANNER will not fit.
BANNER_SHORT = "DEMO DATA - not real revenue"

#: Embedded in demo receipt bodies before hashing.
DEMO_TAG = "isDemo"

#: Every table that can hold a demo row. Order matters for deletion: children
#: first, so the foreign keys (SQLite has them ON, see app/db.py) stay satisfied.
LEDGER_MODELS: tuple[type, ...] = (Receipt, Call, Batch, PaySession, Tool, Author)

_T = TypeVar("_T")


@dataclass(frozen=True)
class DemoSummary:
    """What the dashboard needs to decide how loudly to say `demo`."""

    #: Any demo row at all -> show the banner.
    present: bool
    #: There is demo data and no real data -> everything on screen is fake.
    only_demo: bool
    #: Both kinds present -> the numbers are MIXED, which is the worst case to
    #: display silently; the dashboard should label per-row, not just banner.
    mixed: bool
    counts: dict[str, int]
    real_counts: dict[str, int]
    #: Demo revenue in atomic units, so it can be shown as "of which X is demo".
    demo_captured_atomic: int
    real_captured_atomic: int

    @property
    def total_rows(self) -> int:
        return sum(self.counts.values())

    def as_dict(self) -> dict[str, Any]:
        return {
            "present": self.present,
            "onlyDemo": self.only_demo,
            "mixed": self.mixed,
            "counts": self.counts,
            "realCounts": self.real_counts,
            "demoCapturedAtomic": self.demo_captured_atomic,
            "realCapturedAtomic": self.real_captured_atomic,
            "banner": BANNER if self.present else None,
        }


def mark_demo(obj: _T, *, demo: bool = True) -> _T:
    """Stamp a model instance. The only supported way for the seeder to write.

    Raises rather than silently no-op'ing on a model without the column: a typo
    in a future table name must not produce unlabelled demo rows.
    """
    if not hasattr(obj, "is_demo"):
        raise TypeError(
            f"{type(obj).__name__} has no is_demo column -- add it to the model "
            "and a migration before seeding it"
        )
    obj.is_demo = demo
    return obj


def demo_only(model: type) -> Any:
    """Filter clause for `select(model).where(demo_only(model))`."""
    return model.is_demo.is_(True)


def real_only(model: type) -> Any:
    """Filter clause selecting genuine rows. Use this in any view that reports
    revenue as fact."""
    return model.is_demo.is_(False)


def summary(db: DBSession) -> DemoSummary:
    """Count demo vs real rows across the ledger. One query per table; cheap
    enough to call on every dashboard render because `is_demo` is indexed."""
    counts: dict[str, int] = {}
    real_counts: dict[str, int] = {}
    for model in LEDGER_MODELS:
        name = model.__tablename__
        counts[name] = _count(db, model, True)
        real_counts[name] = _count(db, model, False)

    demo_captured = _sum_captured(db, True)
    real_captured = _sum_captured(db, False)

    present = any(counts.values())
    has_real = any(real_counts.values())
    return DemoSummary(
        present=present,
        only_demo=present and not has_real,
        mixed=present and has_real,
        counts=counts,
        real_counts=real_counts,
        demo_captured_atomic=demo_captured,
        real_captured_atomic=real_captured,
    )


def purge(db: DBSession) -> dict[str, int]:
    """Delete every demo row and nothing else. Returns rows removed per table.

    Children before parents, because SQLite runs with `foreign_keys=ON` (see
    `app/db.py`) and would otherwise refuse. The `is_demo` predicate is on every
    statement: a demo call hanging off a real session is removed, a real call
    hanging off a demo session is not. That is correct -- the flag is per row.

    **Bulk DELETE, not ORM `session.delete()`.** Deleting a `Tool` object
    through the ORM makes SQLAlchemy apply the default relationship cascade to
    `Tool.calls`, which NULLs out `call.tool_id` on every referring row --
    including REAL ones. A cleanup that silently corrupts real ledger rows is
    considerably worse than the demo data it was removing. A bulk delete emits
    exactly the statement asked for and lets the database's own foreign keys
    object if something real still depends on the row.
    """
    from sqlalchemy import delete, func

    removed: dict[str, int] = {}
    for model in LEDGER_MODELS:
        count = int(
            db.exec(select(func.count()).select_from(model).where(demo_only(model))).one() or 0
        )
        if count:
            db.exec(delete(model).where(demo_only(model)))
        removed[model.__tablename__] = count
    db.commit()
    # ORM identity map may still hold objects that no longer exist.
    db.expire_all()
    return removed


def _count(db: DBSession, model: type, demo: bool) -> int:
    clause = demo_only(model) if demo else real_only(model)
    stmt = select(func.count()).select_from(model).where(clause)
    return int(db.exec(stmt).one() or 0)


def _sum_captured(db: DBSession, demo: bool) -> int:
    """Captured revenue, from `call` -- the atom. Summing `pay_session` instead
    would double-count against a partially settled batch."""
    clause = demo_only(Call) if demo else real_only(Call)
    stmt = select(func.sum(Call.captured_atomic)).where(clause)
    return int(db.exec(stmt).one() or 0)
